from django import forms

class dataform(forms.Form):
    fname = forms.CharField(label='fname', max_length=100)
    lname = forms.CharField(label='lname', max_length=30)
    school = forms.CharField(label='school', max_length=100)
    
class finaldataform(forms.Form):
    #date = forms.DateTimeField(label= 'date', auto_now=True, required=False)
    fname = forms.CharField(label='fname', max_length=32)
    lname = forms.CharField(label='lname', max_length=64)
    mname = forms.CharField(label='mname', max_length=32)
    dob = forms.CharField(label='dob', max_length=16)
    birthp = forms.CharField(label='birthp', max_length=64)
    gender = forms.CharField(label='gender', max_length=32)
    genderhide = forms.CharField(label='genderhide', max_length=32 , required=False)  # possibly for the 'other' text input box that appears
    soc = forms.CharField(label='soc', max_length=32)
    school = forms.CharField(label='school', max_length=128)
    maddress = forms.CharField(label='maddress', max_length=64)
    maddress2 = forms.CharField(label='maddress2', max_length=64, required=False)
    maddresscity = forms.CharField(label='maddresscity', max_length=64)
    maddressstate = forms.CharField(label='maddressstate', max_length=64)
    saddress = forms.CharField(label='saddress', max_length=64)
    saddress2 = forms.CharField(label='saddress2', max_length=64, required=False)
    saddresscity = forms.CharField(label='saddresscity', max_length=64)
    saddressstate = forms.CharField(label='saddressstate', max_length=64)
    hphone = forms.CharField(label='hphone', max_length=16)
    unlisted = forms.BooleanField(label='unlisted', required=False)
    father = forms.BooleanField(label='father', required=False)
    mother = forms.BooleanField(label='mother', required=False)
    guardian = forms.BooleanField(label='guardian', required=False)
    fathername = forms.CharField(label='fathername', max_length=32)
    fatherwnum = forms.CharField(label='fatherwnum', max_length=32)
    fathercnum = forms.CharField(label='fathercnum', max_length=32)
    mothername = forms.CharField(label='mothername', max_length=32)
    motherwnum = forms.CharField(label='motherwnum', max_length=32)
    mothercnum = forms.CharField(label='mothercnum', max_length=32)